<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="12" passed="7" failed="5" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-21T18:04:57 IST" name="Default suite" finished-at="2025-02-21T18:05:39 IST" duration-ms="41968">
    <groups>
    </groups>
    <test started-at="2025-02-21T18:04:57 IST" name="Default test" finished-at="2025-02-21T18:05:39 IST" duration-ms="41968">
      <class name="SIP.Customer_QueryDEMO">
        <test-method is-config="true" signature="setup()[pri:0, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:04:57 IST" name="setup" finished-at="2025-02-21T18:05:00 IST" duration-ms="2777" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="sip()[pri:0, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:00 IST" name="sip" finished-at="2025-02-21T18:05:00 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sip -->
        <test-method signature="Dealer_User_Login1()[pri:1, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:00 IST" name="Dealer_User_Login1" finished-at="2025-02-21T18:05:06 IST" duration-ms="5958" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Dealer_User_Login1 -->
        <test-method signature="Click_On_SIP()[pri:2, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:06 IST" name="Click_On_SIP" finished-at="2025-02-21T18:05:10 IST" duration-ms="4030" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Click_On_SIP -->
        <test-method signature="Click_On_Additional_Fillter_To_Clear_Data()[pri:4, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:10 IST" name="Click_On_Additional_Fillter_To_Clear_Data" finished-at="2025-02-21T18:05:15 IST" duration-ms="5587" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Click_On_Additional_Fillter_To_Clear_Data -->
        <test-method signature="Click_On_Customer_Page()[pri:5, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:15 IST" name="Click_On_Customer_Page" finished-at="2025-02-21T18:05:16 IST" duration-ms="439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Click_On_Customer_Page -->
        <test-method signature="Product_Query_Flow()[pri:6, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:16 IST" name="Product_Query_Flow" finished-at="2025-02-21T18:05:24 IST" duration-ms="8280" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[TEST Failed :: Product Query Flow: stale element reference: stale element not found in the current frame
  (Session info: chrome=133.0.6943.100)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '22.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [8f4ead14de6808bf5ead774d85825fe9, clickElement {id=f.F3C059CCE6653EF302A194B91A26F3D7.d.CC21374D5E79469BC2208D783F1492A3.e.119}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 133.0.6943.100, chrome: {chromedriverVersion: 133.0.6943.126 (cffa127ce7b..., userDataDir: C:\Users\AA\AppData\Local\T...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62066}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:62066/devtoo..., se:cdpVersion: 133.0.6943.100, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (8f4ead14de6808bf5ead774d85825fe9)] -> xpath: (//*[text()="View Details"])[2]]
Session ID: 8f4ead14de6808bf5ead774d85825fe9]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: TEST Failed :: Product Query Flow: stale element reference: stale element not found in the current frame
  (Session info: chrome=133.0.6943.100)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '22.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [8f4ead14de6808bf5ead774d85825fe9, clickElement {id=f.F3C059CCE6653EF302A194B91A26F3D7.d.CC21374D5E79469BC2208D783F1492A3.e.119}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 133.0.6943.100, chrome: {chromedriverVersion: 133.0.6943.126 (cffa127ce7b..., userDataDir: C:\Users\AA\AppData\Local\T...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62066}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:62066/devtoo..., se:cdpVersion: 133.0.6943.100, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (8f4ead14de6808bf5ead774d85825fe9)] -> xpath: (//*[text()="View Details"])[2]]
Session ID: 8f4ead14de6808bf5ead774d85825fe9
at org.testng.Assert.fail(Assert.java:99)
at SIP.Customer_QueryDEMO.executeQueryFlow(Customer_QueryDEMO.java:247)
at SIP.Customer_QueryDEMO.Product_Query_Flow(Customer_QueryDEMO.java:85)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Product_Query_Flow -->
        <test-method signature="Validate_Product_Query()[pri:7, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:24 IST" name="Validate_Product_Query" finished-at="2025-02-21T18:05:25 IST" duration-ms="510" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Selected 'Product' does not show in 'Category' after Open Query history expected [null] but found [Product]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Selected 'Product' does not show in 'Category' after Open Query history expected [null] but found [Product]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at SIP.Customer_QueryDEMO.validateQueryStatus(Customer_QueryDEMO.java:254)
at SIP.Customer_QueryDEMO.Validate_Product_Query(Customer_QueryDEMO.java:90)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_Product_Query -->
        <test-method signature="Payment_Query_Flow()[pri:8, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:25 IST" name="Payment_Query_Flow" finished-at="2025-02-21T18:05:29 IST" duration-ms="4139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Payment_Query_Flow -->
        <test-method signature="Validate_Payment_Query()[pri:9, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:29 IST" name="Validate_Payment_Query" finished-at="2025-02-21T18:05:29 IST" duration-ms="507" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status 'CLOSED' not shown when query is closed expected [Closed] but found [Open]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status 'CLOSED' not shown when query is closed expected [Closed] but found [Open]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at SIP.Customer_QueryDEMO.validateQueryStatus(Customer_QueryDEMO.java:256)
at SIP.Customer_QueryDEMO.Validate_Payment_Query(Customer_QueryDEMO.java:101)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_Payment_Query -->
        <test-method signature="Extended_Warranty_Payment_Query()[pri:10, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:29 IST" name="Extended_Warranty_Payment_Query" finished-at="2025-02-21T18:05:30 IST" duration-ms="518" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status 'CLOSED' not shown when query is closed expected [Closed] but found [Open]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status 'CLOSED' not shown when query is closed expected [Closed] but found [Open]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at SIP.Customer_QueryDEMO.validateQueryStatus(Customer_QueryDEMO.java:256)
at SIP.Customer_QueryDEMO.Extended_Warranty_Payment_Query(Customer_QueryDEMO.java:112)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Extended_Warranty_Payment_Query -->
        <test-method signature="Extended_Warranty_Query_Flow()[pri:10, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:30 IST" name="Extended_Warranty_Query_Flow" finished-at="2025-02-21T18:05:34 IST" duration-ms="4081" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Extended_Warranty_Query_Flow -->
        <test-method signature="Maruti_Insurance_Query_Flow()[pri:11, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:34 IST" name="Maruti_Insurance_Query_Flow" finished-at="2025-02-21T18:05:38 IST" duration-ms="4553" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Maruti_Insurance_Query_Flow -->
        <test-method signature="Maruti_Insurance_Query()[pri:12, instance:SIP.Customer_QueryDEMO@22555ebf]" started-at="2025-02-21T18:05:38 IST" name="Maruti_Insurance_Query" finished-at="2025-02-21T18:05:39 IST" duration-ms="516" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Selected 'Maruti Insurance' does not show in 'Category' after Open Query history expected [Extended Warranty] but found [Maruti Insurance]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Selected 'Maruti Insurance' does not show in 'Category' after Open Query history expected [Extended Warranty] but found [Maruti Insurance]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at SIP.Customer_QueryDEMO.validateQueryStatus(Customer_QueryDEMO.java:254)
at SIP.Customer_QueryDEMO.Maruti_Insurance_Query(Customer_QueryDEMO.java:124)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Maruti_Insurance_Query -->
      </class> <!-- SIP.Customer_QueryDEMO -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
